In [3]:
pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 1.3 MB/s  0:00:04a 0:00:010:00:01:02
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
np.__version__

'2.2.6'

### Numpy
- 머신러닝 애플리케이션에서 데이터 추출, 가공, 변환과 같은 데이터 처리 부분을 담당한다.
- 넘파이 기반의 사이킷런을 이해하기 위해서는 넘파이는 필수이다.
- 사이킷런은 직관적이고 간결하기 때문에 상대적으로 개발하기 쉽지만 넘파이는 양도 많고 배울 것도 많다.
- 넘파이 전체를 다 이해하고 공부하는 것은 머신러닝을 포기하게 만들기 때문에  
  기본 문법과 중요 API만 이해하는 것이 전략적으로 좋다.

In [5]:
ndarray1= np.array([1,2,3])
print(type(ndarray1))

print(ndarray1.shape)
print(ndarray1.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [8]:
ar = np.array([[1,3,5],[2,4,6]])
print(type(ar),ar,sep="\n")

print(ar.shape)
print(ar.ndim)

<class 'numpy.ndarray'>
[[1 3 5]
 [2 4 6]]
(2, 3)
2


In [11]:
ndarray1 = np.array([1,2,3])
print(type(ndarray1))
print(ndarray1.dtype)

ndarray1_int8 = ndarray1.astype(np.int8)
print(ndarray1_int8.dtype)

<class 'numpy.ndarray'>
int64
int8


In [13]:
# 4, 5, 6을 ndarray에 담는다
# dtype을 확인한 뒤 float16으로 변경하고 확인한다

ndarray = np.array([4,5,6])
print(type(ndarray),ndarray.dtype,sep="\n")

ndarray_float16 = ndarray.astype(np.float16)
print(ndarray_float16.dtype)

<class 'numpy.ndarray'>
int64
float16


In [36]:
# 1 ~ 10까지의 요소를 ndarray에 담는다
# 각 요소에 5씩 더한다
#ndarray = np.array([data for data in range(1,11)])
ndarray = np.array(list(range(1,11)))
print(ndarray)

print(ndarray+5)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [50]:
np.arange(1,11,dtype=np.float16)
print(np.arange(1,11,dtype=np.float16).shape)
print(np.arange(1,11,dtype=np.float16))

np.zeros(6).reshape(3,-1)
ndarray2 = np.zeros((3,2))
print(ndarray2.shape)
print(ndarray2)

# 1차원 3칸 배열 요소 모두 1로 초기화
print(np.ones((3,)))
print(np.ones((1,3),dtype=np.int8).dtype)

(10,)
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1.]
int8


In [59]:
ndarray1 = np.arange(8)
print(ndarray1)

print(ndarray1.reshape((2,2,-1)))
print(ndarray1.reshape(2,2,-1))

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [62]:
ndarray1.reshape((-1,2))
ndarray1.reshape((4,2))

# ndarray1을 1열로 변환
ndarray1.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [75]:
# axis 0이 10인 shape이면서 모든 원소가 0, dtype은 int32인 ndarray만들기
# axis 0이 3, axis1이 4인 shape이면서 모든 원소가 1인 ndarray 만들기
# axis 0이 5, 각 요소가 0~4인 ndarray 만들기

# 아래의 ndarray1이 주어졌을 때 순서대로 문제를 해결한다.
# 2 Dimension, axis 1은 2로 변경
# 2 Dimension, axis 0은 8로 변경
# 3 Dimension으로 변경
# ndarray3을 axis 1이 1인 2차원 ndarray로 변환
# ndarray3을 1 Dimension으로 변환
ndarray1= np.arange(start=0,stop=16)

In [76]:
print(np.zeros((10,),dtype=np.int32))
print(np.ones((3,4)))
print(np.arange(0,5))

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3 4]


In [80]:
print(ndarray1)

np_2dim_axis1_2 = ndarray1.reshape((-1,2))
print(np_2dim_axis1_2)

np_2dim_axis0_8= ndarray1.reshape((8,-1))
print(np_2dim_axis0_8)

np_3dim = ndarray1.reshape((8,1,-1))
print(np_3dim)

np_3dim_to_2dim = np_3dim.reshape((-1,1))
print(np_3dim_to_2dim)

# np_3dim_to_1dim = np_3dim.reshape((-1,)) 
np_3dim_to_1dim = np_3dim.flatten()
print(np_3dim_to_1dim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[[ 0  1]]

 [[ 2  3]]

 [[ 4  5]]

 [[ 6  7]]

 [[ 8  9]]

 [[10 11]]

 [[12 13]]

 [[14 15]]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [81]:
ndarray1 = np.arange(start=1, stop=21)
ndarray2 = ndarray1.reshape((5, -1))
print(ndarray2)

# 2행의 4번째 숫자 출력
# 1~100 중 짝수만 출력
# 위에서 구한 짝수들을 axis 0이 10인 2차원 배열로 변환 후 82~100까지 추출
# 아래의 ndarray1 요소 중 1의 자리수가 2인 수들만 추출하기
ndarray1 = np.arange(start=1, stop=101)
# 1~49요소 중 2와 5의 공배수 추출하기
# 위에서 추출한 공배수 중 20이상인 값만 추출하기

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [88]:
print(ndarray2[1,3])

ndarray1 = np.arange(start=1,stop=101)
print(ndarray1[ndarray1 % 2 == 0])

ndarray1_even = ndarray1[ndarray1 % 2 == 0]
ndarray1_even = ndarray1_even.reshape((10,-1))
print(ndarray1_even[ndarray1_even >=82])

ndarray1 = np.arange(start=1, stop=101)
ndarray1_2 = ndarray1[ndarray1 % 10 == 2]
print(ndarray1_2)

ndarray1 = np.arange(start=1,stop=50)
print(ndarray1[ndarray1 % 10 == 0])
ndarray1_10 = ndarray1[ndarray1 % 10 == 0]
print(ndarray1_10[ndarray1_10>=20])
                





8
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[ 82  84  86  88  90  92  94  96  98 100]
[ 2 12 22 32 42 52 62 72 82 92]
[10 20 30 40]
[20 30 40]


In [89]:
# 제로백이 빠른 순으로 자동차 이름 정렬하기
cars = np.array(['Lamborghini', 'Mclaren', 'Benz', 'Bentley', 'The New Morning'])
zero100 = np.array([2.8, 2.9, 5.2, 3.7, 13.5])

In [101]:
sorted_zero100 = np.argsort(zero100)
print(cars[sorted_zero100])

['Lamborghini' 'Mclaren' 'Bentley' 'Benz' 'The New Morning']


In [95]:
# 데이터를 분석하여, 각 수치별 오름차순 및 내림차순 후 이름을 출력하세요.
# [[과일이름], [가격]], 가격별 내림차순
array1 = [['Mango', 'Apple', 'Pear', 'Pitch', 'Melon'], [1500, 1800, 2000, 2500, 8500]]

In [129]:
array1 = np.array(array1)
print(array1)
sorted_array1_price = np.argsort(array1[1])
sorted_array1_fruit = np.argsort(array1[0])
print(array1,array1[0][sorted_array1_price],sep="\n",end="\n\n")
print(array1,array1[0][sorted_array1_price[::-1]],sep="\n")

[['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']
 ['1500' '1800' '2000' '2500' '8500']]
[['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']
 ['1500' '1800' '2000' '2500' '8500']]
['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']

[['Mango' 'Apple' 'Pear' 'Pitch' 'Melon']
 ['1500' '1800' '2000' '2500' '8500']]
['Melon' 'Pitch' 'Pear' 'Apple' 'Mango']


In [132]:
a = np.array([[1,2,3],[1,2,1],[1,0,3]])
b = np.array([[1,3,5]])

w = np.linalg.inv(a) @ b.T

print(w)

[[ 8.]
 [-2.]
 [-1.]]


In [138]:
a = np.array([[1,2,3],
            [1,2,1],
            [1,0,3],
            [1,5,2]])
b = np.array([1,3,5,55])
x,residuals,_,_ = np.linalg.lstsq(a,b)
print(x)
print(residuals)

[-21.5         11.76666667   4.9       ]
[464.13333333]
